### ISSUE TITLE
log_reg_hd refactoring: round 1

### ISSUE THREAD

**Issue by mstaniak** [StatsIMUWr/ASEstimator#8]
- [x] Move lines 11-16 of reg_log.R to a separate function called `get_gamma_estimator`
- [x] Stop using dollar (use [[)
- [x] Compute solutions to equations once, not twice (lines 21-22 of reg_log.R)
- [x] Move lines 24-25 to a separate functio ncalled `get_mle_estimator`
- [x] length(X[1, ]) -> ncol(X)
- [x] Remove variable assignments, if we only use the objects once?

**Comment by AleksandraSteiner** [comment]
1. I moved these lines as a function to estimate_functions.R. I put there estimate_gamma, X and Y as arguments, we need X and Y to estimate gamma.
2. done
3. I save solutions to 'solution' as a vector of numbers and then I save its first two elements to alpha_star and sigma_star respectively. Is there an easier way?
4. done
5. done
6. Which variables do You mean?

**Comment by mstaniak** [comment]
There should be an assignment (gamma <- get_gamma_estimator(X, Y, estimate_gamma)), 
you don't need to do as.numeric(solution), just use double square bracket [[

**Comment by mstaniak** [comment]
The ones that you use only once(: 
I'm not sure they need a name, as long its clear what they are
